# Copyright (c) 2026 rkwithb (https://github.com/rkwithb)
# Licensed under CC BY-NC 4.0 (Non-Commercial Use Only)
# Disclaimer: Use at your own risk. The author is not responsible for any damages.

"""
core/export.py

JS file generation for plurk-fav.
- base36_encode()    : convert a plurk_id integer to its base-36 URL slug
- export_js_files()  : write per-month JS files and manifest.js from SQLite
- reexport_from_db() : re-export all months from DB without any API call

Output structure (backup_js/):
    YYYY_MM.js      one file per month, contains trimmed plurk objects
    manifest.js     list of all available month keys, newest first

Trimmed JS object fields (raw_json is NOT written to JS files):
    plurk_id, posted, content_raw, owner_id, nick_name,
    plurk_type, plurk_url, tags

response_count and favorite_count are excluded from JS files in v1 —
they remain in raw_json in the DB only. Deferred to v2.

Tags are appended via a LEFT JOIN on plurk_tags/tags at export time.
If the user adds or removes tags in full mode (Flask), JS files become
stale and must be regenerated by running a backup or full re-export.

Month filtering uses the posted2 column (ISO 8601) via SQL LIKE —
no Python-level date parsing needed in the export loop.

TRACK_FILE is not used — affected_months is passed directly as a set.
"""

import json
import os
import sqlite3
from typing import Callable, Set

from core.logger import get_logger

logger = get_logger()

# Fields to extract from raw_json and include in the JS output.
# Everything else (content, qualifier, lang, response_count, favorite_count,
# replurker_id, etc.) stays in DB only.
# response_count and favorite_count deferred to v2.
_JS_FIELDS = (
    "plurk_id",
    "posted",
    "content_raw",
    "owner_id",
    "nick_name",
    "plurk_type",
)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def base36_encode(number: int) -> str:
    """
    Convert a positive integer to its base-36 string representation.
    Used to build Plurk post URLs: https://www.plurk.com/p/<base36(plurk_id)>
    """
    if number == 0:
        return "0"
    chars = "0123456789abcdefghijklmnopqrstuvwxyz"
    result = ""
    while number:
        number, i = divmod(number, 36)
        result = chars[i] + result
    return result


def _build_plurk_object(row: sqlite3.Row, tag_map: dict) -> dict:
    """
    Build a trimmed plurk dict for JS output from a DB row and tag lookup.

    Args:
        row:     sqlite3.Row with raw_json and plurk_id columns
        tag_map: dict mapping plurk_id -> list of tag name strings

    Returns:
        Trimmed dict ready for JSON serialisation into the JS file.
    """
    raw = json.loads(row["raw_json"])
    plurk_id = row["plurk_id"]

    obj = {field: raw.get(field) for field in _JS_FIELDS}
    obj["plurk_url"] = f"https://www.plurk.com/p/{base36_encode(plurk_id)}"
    obj["tags"] = tag_map.get(plurk_id, [])

    return obj


def _fetch_tag_map(conn: sqlite3.Connection, plurk_ids: list) -> dict:
    """
    Fetch all tags for the given plurk_ids in one query.
    Returns a dict mapping plurk_id -> [tag_name, ...].

    Args:
        conn:       open database connection
        plurk_ids:  list of plurk_id integers to look up

    Returns:
        dict[int, list[str]]
    """
    if not plurk_ids:
        return {}

    placeholders = ",".join("?" * len(plurk_ids))
    cursor = conn.cursor()
    cursor.execute(
        f"""
        SELECT pt.plurk_id, t.name
        FROM plurk_tags pt
        JOIN tags t ON pt.tag_id = t.id
        WHERE pt.plurk_id IN ({placeholders})
        """,
        plurk_ids,
    )

    tag_map: dict = {}
    for plurk_id, name in cursor.fetchall():
        tag_map.setdefault(plurk_id, []).append(name)
    return tag_map


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def export_js_files(
    conn: sqlite3.Connection,
    backup_dir: str,
    affected_months: Set[str],
    on_log: Callable[[str], None] = lambda msg: None,
) -> None:
    """
    Write (or rewrite) per-month JS files for the given months, then
    regenerate manifest.js to reflect all available months.

    In full-backup mode, pass all months derived from the DB.
    In incremental/date mode, pass only the months that received new rows.
    Passing an empty set is a no-op (nothing to write).

    Args:
        conn:             open database connection
        backup_dir:       absolute path to the backup_js/ output folder
        affected_months:  set of "YYYY_MM" strings to regenerate
        on_log:           callback for GUI log area messages
    """
    if not affected_months:
        logger.debug("export: no affected months — skipping JS export")
        return

    from core.i18n import t

    sorted_months = sorted(affected_months)
    on_log(t("log_export_js", months=" ".join(sorted_months)))
    logger.info("export: writing JS for months: %s", sorted_months)

    cursor = conn.cursor()
    cursor.row_factory = sqlite3.Row

    for ym in sorted_months:
        # posted2 format: "YYYY-MM-DD HH:MM:SS" — LIKE 'YYYY-MM%' filters by month in SQL
        iso_prefix = ym.replace("_", "-")

        cursor.execute(
            """
            SELECT plurk_id, raw_json
            FROM favorites
            WHERE posted2 LIKE ?
            ORDER BY plurk_id DESC
            """,
            (f"{iso_prefix}%",),
        )
        month_rows = cursor.fetchall()

        if not month_rows:
            logger.debug("export: no rows found for %s — skipping", ym)
            continue

        # Fetch tags for all plurks in this month in one query
        plurk_ids = [row["plurk_id"] for row in month_rows]
        tag_map = _fetch_tag_map(conn, plurk_ids)

        # Build trimmed objects
        plurks = [_build_plurk_object(row, tag_map) for row in month_rows]

        # Write YYYY_MM.js
        file_path = os.path.join(backup_dir, f"{ym}.js")
        try:
            with open(file_path, "w", encoding="utf-8") as f:
                f.write("if (!window.BackupData) window.BackupData = { plurks: {} };\n")
                f.write(
                    f'BackupData.plurks["{ym}"] = '
                    f"{json.dumps(plurks, ensure_ascii=False)};"
                )
            logger.debug("export: wrote %s (%d plurks)", file_path, len(plurks))
        except Exception as e:
            logger.error("export: failed to write %s — %s", file_path, e)

    # Regenerate manifest.js from all JS files currently in backup_dir
    _write_manifest(backup_dir)
    on_log(t("log_export_done"))
    logger.info("export: done")


def reexport_from_db(
    conn: sqlite3.Connection,
    backup_dir: str,
    on_log: Callable[[str], None] = lambda msg: None,
) -> None:
    """
    Re-export all months currently in the DB to JS files, without any API call.
    Intended for use after tag edits or manual DB changes to refresh the viewer.

    Collects all distinct YYYY_MM values from the posted2 column, then delegates
    to export_js_files() for the actual file writing.

    Args:
        conn:       open database connection
        backup_dir: absolute path to the backup_js/ output folder
        on_log:     callback for GUI log area messages
    """
    cursor = conn.cursor()
    cursor.execute(
        "SELECT DISTINCT strftime('%Y', posted2) || '_' || strftime('%m', posted2) "
        "FROM favorites WHERE posted2 IS NOT NULL"
    )
    all_months = {row[0] for row in cursor.fetchall()}

    logger.info("reexport: collected %d months from DB", len(all_months))
    export_js_files(conn, backup_dir, all_months, on_log)


def _write_manifest(backup_dir: str) -> None:
    """
    Scan backup_dir for YYYY_MM.js files and write manifest.js.
    manifest.js contains the list of available month keys, newest first.
    """
    all_months = sorted(
        [f[:-3] for f in os.listdir(backup_dir)
         if f.endswith(".js") and f != "manifest.js"],
        reverse=True,
    )

    manifest_path = os.path.join(backup_dir, "manifest.js")
    try:
        with open(manifest_path, "w", encoding="utf-8") as f:
            f.write("if (!window.BackupData) window.BackupData = { plurks: {} };\n")
            f.write(f"BackupData.months = {json.dumps(all_months)};")
        logger.debug("export: manifest written — %d months", len(all_months))
    except Exception as e:
        logger.error("export: failed to write manifest.js — %s", e)
